spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client1515151515
  cloud:
   stream:
     kafka:
       binder:
         brokers: 39.97.170.86

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka
    
info:
  app.name: microservice-config-client-dev
  company.name: yc
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client
  cloud:
   stream:
     kafka:
       binder:
         brokers: 39.97.170.86

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka
    
    
info:
  app.name: microservice-config-client-beta
  company.name: hyycinfo
